server.port=8081
spring.application.name=student-service
spring.datasource.url=jdbc:postgresql://student-management-pg.postgres.database.azure.com:5432/student_db?sslmode=require

spring.datasource.username=pgadminuser

spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:9000/eureka/}
eureka.instance.prefer-ip-address=true
